LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE := libteec
LOCAL_MODULE_CLASS := SHARED_LIBRARIES

ifdef TARGET_2ND_ARCH
LOCAL_MULTILIB := both
LOCAL_MODULE_PATH_64 := $(TARGET_OUT)/lib64
LOCAL_MODULE_PATH_32 := $(TARGET_OUT)/lib
LOCAL_SRC_FILES_64 := lib64/libteec.so
LOCAL_SRC_FILES_32 := lib/libteec.so
else
LOCAL_SRC_FILES := lib/libteec.so
LOCAL_MODULE_PATH := $(TARGET_OUT)/lib
endif

include $(BUILD_PREBUILT)
