LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := power.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_RELATIVE_PATH := hw

LOCAL_SHARED_LIBRARIES := liblog
LOCAL_SHARED_LIBRARIES += libutils
LOCAL_SHARED_LIBRARIES += libcutils

LOCAL_SRC_FILES := power.cpp
LOCAL_SRC_FILES += power_utils.cpp
LOCAL_SRC_FILES += power_base.cpp
LOCAL_SRC_FILES += power_cpu.cpp
LOCAL_SRC_FILES += power_gpu.cpp

LOCAL_C_INCLUDES += $(LOCAL_PATH)

include $(BUILD_SHARED_LIBRARY)
