rm=/bin/rm -f
CC= g++
CXX= g++
PROGRAM=db_transfer

SRCS = db_transfer.cpp 
OBJS = db_transfer.o

.c.o:
	$(rm) -f $@
	$(CC) $(CFLAGS) -c $*.c

all: $(PROGRAM)
	
$(PROGRAM): $(OBJS)
	$(CXX) -O0 -o $(PROGRAM) $(LDFLAGS) -Wl,--start-group $(OBJS) $(LIBS) -Wl,--end-group 
		
clean:
	@rm -f $(OBJS) $(PROGRAM) core *~
