-include ../../../../../../branch_src_sharedMemory_integration/Tools/MConfig/.config
include ../../../../../../include/MakeConfig

rm=/bin/rm -f
CC= $(MYCC)
CXX= $(MYCXX)
PROGRAM=db_transfer

LDFLAGS += -static

SRCS = db_transfer.cpp 
OBJS = db_transfer.o

.c.o:
	$(rm) -f $@
	$(CC) $(CFLAGS) -c $*.c

all: $(PROGRAM)
	
$(PROGRAM): $(OBJS)
	$(CXX) -O0 -o $(PROGRAM) $(LDFLAGS) -Wl,--start-group $(OBJS) $(LIBS) -Wl,--end-group 
		
clean:
	@rm -f $(OBJS) $(PROGRAM) core *~
