/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_DATA_H_RPCGEN
#define _RPCBASEDS_DATA_H_RPCGEN
typedef unsigned int u_int;

typedef int HRESULT;

struct RPCRES_LONG {
	HRESULT result;
	u_int data;
};
typedef struct RPCRES_LONG RPCRES_LONG;

struct USB_DEVICE_CONFIG_INFO {
	HRESULT ret;
	u_int usb_ai_samplerate;
	u_int usb_ai_format;
	u_int usb_ai_chnum;
};
typedef struct USB_DEVICE_CONFIG_INFO USB_DEVICE_CONFIG_INFO;

struct RPC_CONNECTION {
	u_int srcInstanceID;
	u_int srcPinID;
	u_int desInstanceID;
	u_int desPinID;
	u_int mediaType;
};
typedef struct RPC_CONNECTION RPC_CONNECTION;

struct RPC_SEND_LONG {
	u_int instanceID;
	u_int pinID;
	u_int data;
};
typedef struct RPC_SEND_LONG RPC_SEND_LONG;

#endif /* !_RPCBASEDS_DATA_H_RPCGEN */
